version: '3.8'

services:
  productservice:
    build: .././src/ProductService/ProductService.API
    ports: ["5001:80"]
    depends_on: [rabbitmq]

  orderservice:
    build: .././src/OrderService/OrderService.API
    ports: ["5002:80"]
    depends_on: [rabbitmq]

  gateway:
    build: .././gateway/YARP.Gateway
    ports: ["80:80"]
    depends_on: [productservice, orderservice]

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports: ["9200:9200"]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports: ["5601:5601"]

  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
